# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import src.wallet as module_0


def test_case_0():
    wallet_system_0 = module_0.WalletSystem()
    with pytest.raises(AssertionError):
        wallet_system_0.get_payment_methods(wallet_system_0)


def test_case_1():
    module_0.WalletSystem()


def test_case_2():
    wallet_system_0 = module_0.WalletSystem()
    with pytest.raises(AssertionError):
        wallet_system_0.set_spending_limits(wallet_system_0)


def test_case_3():
    wallet_system_0 = module_0.WalletSystem()
    bool_0 = wallet_system_0.verify_invariants()
    assert bool_0 is True


def test_case_4():
    wallet_system_0 = module_0.WalletSystem()
    wallet_system_0.set_pin(wallet_system_0, wallet_system_0)


def test_case_5():
    wallet_system_0 = module_0.WalletSystem()
    with pytest.raises(AssertionError):
        wallet_system_0.withdraw_funds(
            wallet_system_0, wallet_system_0, wallet_system_0
        )


def test_case_6():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "+hb@m;$qj2I;Z9\x0cAn>_"
    wallet_system_0.create_account(str_0, wallet_system_0, wallet_system_0)


def test_case_7():
    wallet_system_0 = module_0.WalletSystem()
    wallet_system_0.authenticate_pin(wallet_system_0, wallet_system_0)


def test_case_8():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "Kq|[EDI9+aa>\\(ii)"
    with pytest.raises(AssertionError):
        wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_9():
    wallet_system_0 = module_0.WalletSystem()
    with pytest.raises(AssertionError):
        wallet_system_0.add_funds(wallet_system_0, wallet_system_0)


def test_case_10():
    wallet_system_0 = module_0.WalletSystem()
    with pytest.raises(AssertionError):
        wallet_system_0.track_transactions(wallet_system_0, page_size=wallet_system_0)


def test_case_11():
    wallet_system_0 = module_0.WalletSystem()
    wallet_system_0.add_payment_method(wallet_system_0, wallet_system_0)


def test_case_12():
    wallet_system_0 = module_0.WalletSystem()
    with pytest.raises(AssertionError):
        wallet_system_0.real_time_update(wallet_system_0, wallet_system_0)


def test_case_13():
    wallet_system_0 = module_0.WalletSystem()
    wallet_system_0.transfer(wallet_system_0, wallet_system_0, wallet_system_0)


def test_case_14():
    wallet_system_0 = module_0.WalletSystem()
    bool_0 = wallet_system_0.verify_invariants()
    assert bool_0 is True
    with pytest.raises(AssertionError):
        wallet_system_0.apply_interest(bool_0)


def test_case_15():
    str_0 = "\\"
    wallet_system_0 = module_0.WalletSystem()
    none_type_0 = None
    wallet_system_0.create_account(str_0, str_0, none_type_0)


def test_case_16():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "*\r"
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_17():
    str_0 = "n'x.@\\Sh(ow[dZ-^0bP"
    wallet_system_0 = module_0.WalletSystem()
    none_type_0 = None
    with pytest.raises(AssertionError):
        wallet_system_0.create_account(str_0, str_0, none_type_0)


def test_case_18():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "\t:,m"
    set_0 = {wallet_system_0}
    wallet_system_0.create_account(str_0, str_0, set_0)


def test_case_19():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "92e&!_d=4wa2sc\r_0i\t"
    none_type_0 = None
    wallet_system_0.create_account(wallet_system_0, none_type_0, str_0)


def test_case_20():
    wallet_system_0 = module_0.WalletSystem()
    float_0 = -1322.4
    with pytest.raises(AssertionError):
        wallet_system_0.apply_interest(float_0)


def test_case_21():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "'#Y"
    str_1 = ""
    wallet_system_0.create_account(str_0, str_1, wallet_system_0)


def test_case_22():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = ""
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_23():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = ""
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_24():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "\t:,m"
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_25():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "\t:,m"
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_26():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "+<AU"
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_27():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "AT"
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_28():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "TFgC]6-\\).+\\Fc[+^E"
    with pytest.raises(AssertionError):
        wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_29():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "AT"
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_30():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "AT"
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_31():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = ""
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_32():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "."
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_33():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = ""
    str_1 = ""
    str_2 = ""
    wallet_system_0.create_account(str_1, str_2, str_0)


def test_case_34():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "d"
    str_1 = "-"
    str_2 = "D"
    wallet_system_0.create_account(str_1, str_2, str_0)


def test_case_35():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "(\nE+>(-OUIcM jyz#G"
    with pytest.raises(AssertionError):
        wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_36():
    wallet_system_0 = module_0.WalletSystem()
    bool_0 = wallet_system_0.verify_invariants()
    assert bool_0 is True
    str_0 = ""
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_37():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "HFLm"
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_38():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "4WBe$_e@[VykX!"
    none_type_0 = wallet_system_0.create_account(str_0, str_0, str_0)
    assert len(wallet_system_0.balances) == 1
    wallet_system_0.set_pin(str_0, none_type_0)


def test_case_39():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "5 <z.!"
    with pytest.raises(AssertionError):
        wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_40():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "TFgC]6-\\).+\\Fc[+^E"
    with pytest.raises(AssertionError):
        wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_41():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "."
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_42():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "."
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_43():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "HFLm"
    wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_44():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "\">eWXrYVF'M\x0cg\t=d&"
    with pytest.raises(AssertionError):
        wallet_system_0.create_account(str_0, str_0, str_0)


def test_case_45():
    wallet_system_0 = module_0.WalletSystem()
    str_0 = "\">eWXrYVF'M\x0cg\t=d&"
    with pytest.raises(AssertionError):
        wallet_system_0.create_account(str_0, str_0, str_0)
