# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import src.walletBackup as module_0


def test_case_0():
    wallet_system_0 = module_0.WalletSystem()
    wallet_system_0.get_payment_methods(wallet_system_0)


def test_case_1():
    wallet_system_0 = module_0.WalletSystem()
    wallet_system_0.add_payment_method(wallet_system_0, wallet_system_0)


def test_case_2():
    wallet_system_0 = module_0.WalletSystem()
    wallet_system_0.authenticate_pin(wallet_system_0, wallet_system_0)


def test_case_3():
    wallet_system_0 = module_0.WalletSystem()
    with pytest.raises(AssertionError):
        wallet_system_0.apply_interest(wallet_system_0)


def test_case_4():
    wallet_system_0 = module_0.WalletSystem()
    wallet_system_0.set_pin(wallet_system_0, wallet_system_0)


def test_case_5():
    int_0 = -294
    wallet_system_0 = module_0.WalletSystem()
    with pytest.raises(AssertionError):
        wallet_system_0.apply_interest(int_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    wallet_system_0 = module_0.WalletSystem()
    bool_0 = True
    wallet_system_0.apply_interest(bool_0)
